### ISSUE TITLE
thx

### ISSUE THREAD

**Issue by newbie-hue** [frogc0de/TikTok-API#1]
i want to search videos list of tiktok,this can help me?

**Comment by frogc0de** [comment]
This api is specifically for getting information about a specific video, you need to add another function if you want to search more data like user profiles and recommendations. This is totally possible, but I am not sure if I will add it to this api, try doing some of your own research.

**Comment by newbie-hue** [comment]
I got it and you're one of the best people I've ever met,and use your method of the class of genXGorgon and genXKhronos.thx.
