### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by newbie-hue** [frogc0de/TikTok-API#2]
would I  get video infos and profile of use, what i should do?thx

**Comment by newbie-hue** [comment]
i want to use your class of TTAPI to get the information of video ,can you Can you give me a detailed example.such as the_url_of_the_video。

**Comment by newbie-hue** [comment]
i find a bug in the TikTok-Algorithm , about gzip.
and I don't think what is the function of   test_vidoe will work.
maybe the interface is chanllenge.
I've spent hours trying to fix it, but I've failed

**Comment by newbie-hue** [comment]
i find a bug in the TikTok-Algorithm , about gzip.
and I don't think what is the function of test_vidoe will work.
maybe the interface is changed.
I've spent hours trying to fix it, but I've failed

**Comment by newbie-hue** [comment]
I agonized for a long time

**Comment by frogc0de** [comment]
I deleted the tiktok-algorithm repository because it is an old file and no longer works, if you want to use the tiktok functions you should use this repository.

**Comment by frogc0de** [comment]
I will update the tiktok api and provide you with an example.py file, I hope it helps.

**Comment by newbie-hue** [comment]
This is great. It's working

**Comment by newbie-hue** [comment]
thank you very very very very very very very very very very very very very very very very very very very very very ......... much

**Comment by frogc0de** [comment]
If you want to get data about a specific user and their posts then this is totally possible. If you want, I can include a getUser and listPosts functions, it should be quite easy.

**Comment by newbie-hue** [comment]
Thank you very much. Can I help you in any way.
i cann't get the interface from app.
and i need it.
i have  a try.

**Comment by frogc0de** [comment]
You have trouble accessing the tiktok api?

**Comment by frogc0de** [comment]
I used a mitm proxy to be able to intercept the tiktok application which is how I know about the different requests.

**Comment by newbie-hue** [comment]
I can't catch the bag of app

**Comment by frogc0de** [comment]
You can't use the browser app you must use the app on your phone to do this and be logged into an account. After that I got https://mitmproxy.org/ and connected it to my device allowing me to intercept the packages.

**Comment by newbie-hue** [comment]
Thank you for your advice. I'll learn it right away

**Comment by newbie-hue** [comment]
Can you get me the port, please? I'd like to take a test.
Just like https://api-h2.tiktokv.com/aweme/v1/user/following/list/?user_id=6805205154263122946&max_time=1627438521&count=20&offset=40&source_type=2&address_book_access=2&gps_access=2&retry_type=no_retry&iid=6984616016341567234&device_id=6984612823663150593&ac=wifi&channel=googleplay&aid=1180&app_name=trill&version_code=603&version_name=6.0.3&device_platform=android&ab_version=6.0.3&ssmix=a&device_type=Pixel&device_brand=google&language=zh&os_api=29&os_version=10&openudid=f12e8c952faa95cc&manifest_version_code=603&resolution=1080*1794&dpi=420&update_version_code=6030&_rticket=1626249683824&app_language=en&current_region=SG&pass-route=1&timezone_offset=28800&sys_region=CN&uoo=0&is_my_cn=1&pass-region=1&timezone_name=Asia/Shanghai&build_number=6.0.3&region=US&residence=SG&ts=1639021645
036141108000fc6c1ff2b51fbe74c6b04a86b996c439896acc26

**Comment by frogc0de** [comment]
Oh so you are trying to receive data from https://api-h2.tiktokv.com/aweme/v1/user/following/list/?user_id=6805205154263122946 ?

**Comment by frogc0de** [comment]
Let me write you a quick script

**Comment by newbie-hue** [comment]
If you can include the functions of getUser and listPosts , that's great.

**Comment by newbie-hue** [comment]
thank you very very very very very very very very very much

**Comment by frogc0de** [comment]
yup it is easy

**Comment by newbie-hue** [comment]
hhhhhhhh,you are so cool!!!!!!!!!!

**Comment by newbie-hue** [comment]
Are you using a real phone? Or Mobile phone simulator？

**Comment by frogc0de** [comment]
I used bluestacks because it did not work on my real phone, so I intercepted a virtual android machine.

**Comment by frogc0de** [comment]
So ok, all the api requests functions use TTAPIRequest(path, query, deviceParams) which can be used to get any path of the api. So, in your case you would do this : TTAPI().TTAPIRequest("/aweme/v1/user/following/list/",{"user_id":"6805205154263122946"},TTAPI().deviceParams)

**Comment by newbie-hue** [comment]
the interface of following  not the interface I want.

**Comment by frogc0de** [comment]
Yes I know, I will add a function latter, but can you confirm that this script returns the result you want?

**Comment by newbie-hue** [comment]
It is a personal page, including the number of followers and followers and so on.

**Comment by frogc0de** [comment]
Yeah, that looks like it

**Comment by frogc0de** [comment]
Ok, so I will add the function listFollowing(userId) latter and hope it helps

**Comment by newbie-hue** [comment]
thx

**Comment by frogc0de** [comment]
Also using the url you posted you can actually generate your own deviceParams to make it more reliable. Simply do **TTAPI().getDeviceParams("https://api-h2.tiktokv.com/aweme/v1/user/following/list/?user_id=6805205154263122946&max_time=1627438521&count=20&offset=40&source_type=2&address_book_access=2&gps_access=2&retry_type=no_retry&iid=6984616016341567234&device_id=6984612823663150593&ac=wifi&channel=googleplay&aid=1180&app_name=trill&version_code=603&version_name=6.0.3&device_platform=android&ab_version=6.0.3&ssmix=a&device_type=Pixel&device_brand=google&language=zh&os_api=29&os_version=10&openudid=f12e8c952faa95cc&manifest_version_code=603&resolution=1080*1794&dpi=420&update_version_code=6030&_rticket=1626249683824&app_language=en&current_region=SG&pass-route=1&timezone_offset=28800&sys_region=CN&uoo=0&is_my_cn=1&pass-region=1&timezone_name=Asia/Shanghai&build_number=6.0.3&region=US&residence=SG&ts=1639021645")**

Which will return this dictionary:
{'os_api': '29', 'device_type': 'Pixel', 'app_name': 'trill', 'version_name': '6.0.3', 'channel': 'googleplay', 'device_platform': 'android', 'iid': '6984616016341567234', 'version_code': '603', 'device_id': '6984612823663150593', 'os_version': '10', 'aid': '1180'}

After which you can set the TTAPI.deviceParams to this dictionary

**Comment by newbie-hue** [comment]
Thank you for your explanation, I understand that.

**Comment by newbie-hue** [comment]
Will the phone parameters and tiktok version affect my access to the interface?

**Comment by newbie-hue** [comment]
Is the functions of getUser and listPosts working?

**Comment by newbie-hue** [comment]
i move the ca to the path of /system/etc/security/cacerts,but i can't the clear text.

**Comment by newbie-hue** [comment]
hello

**Comment by newbie-hue** [comment]
hello

**Comment by frogc0de** [comment]
Sorry, api currently not functioning because of some problem, after I figure it out, I will update it.

**Comment by frogc0de** [comment]
Api updated to version 0.0.12

Fixes: Changed expired device parameters

Updates: The following functions are now available:
(I hope this is what you need)

getPost(post_id) #Gets a post.

getUser(user_id) #Gets a user's profile.

listPosts(user_id) #Lists a user's posts.

listFollowers(user_id) #Lists the users that follow the specified user.

listFollowing(user_id) #Lists the users that the specified user follows.

**Comment by frogc0de** [comment]
> Will the phone parameters and tiktok version affect my access to the interface?

The parameters you send do not affect the api usage, it only checks if the parameters are signed or unsigned. If you give it random parameters, it will return a blank response, you must give it signed parameters to get a normal response.

**Comment by newbie-hue** [comment]
this's so cool  ,it is working.....

**Comment by newbie-hue** [comment]
Thank you for your kindness and generosity, which has been a great inspiration to me

**Comment by newbie-hue** [comment]
Can we add a contact number？

**Comment by frogc0de** [comment]
> Can we add a contact number？

The best and quickest way to contact me about this API would be to create an issue. I will maintain this API at times I am not busy and stop supporting it if tiktok starts using a completely different way to access the API. The only problem I am having is with device parameters because they need to be updated about once in a while, I am hoping to find an automated solution or permanent device parameters if possible. _If all your questions were answered then you can close this issue. _

**Comment by newbie-hue** [comment]
this's OK .it was of great help to me.I'm going to close this issue.

**Comment by frogc0de** [comment]
Ok
