### ISSUE TITLE
Code not working for follow user api endpoint

### ISSUE THREAD

**Issue by freevbuckz** [frogc0de/TikTok-API#4]
I setup the code and it worked for most of the endpoint I used here https://coding.vivoliker.com/print/OLP95IXSOo but not working for follow user and unfollow user endpoint.

**Comment by Petr2282** [comment]
> I setup the code and it worked for most of the endpoint I used here https://coding.vivoliker.com/print/OLP95IXSOo but not working for follow user and unfollow user endpoint.

Follow and like endpoints are much more sensitive and they need also valid device register,xlog,applog,ttencrypt and not only x-gorgon,x-khoronos.

**Comment by frogc0de** [comment]
As I stated this api is not for controlling a user account and only works for gathering data which is why you are getting this problem. If you want, I can attempt to add a way to control a user account, but this would require logging in and getting much more parameters.

**Comment by freevbuckz** [comment]
> As I stated this api is not for controlling a user account and only works for gathering data which is why you are getting this problem. If you want, I can attempt to add a way to control a user account, but this would require logging in and getting much more parameters.

Yes please add if possible, I login manually and get all parameters needed, getting the parameters is not an issue, I do everything manually. I wish you can add the one for controlling user account

**Comment by frogc0de** [comment]
If I am correct, then this could be done by logging in using the api and receiving the x tt token. Then making the requests with the device parameters, gorgons and the token, I will try checking.

**Comment by frogc0de** [comment]
I think the best way to get this to work is not by using the device api but the web api because it is easier to inspect it.

**Comment by Petr2282** [comment]
> I think the best way to get this to work is not by using the device api but the web api because it is easier to inspect it.

Web api have security headers for like and sub from shape security and it is hard to understand how they get it,because they use other service to analyse many data of web fingerprint with neural network(f5 shape security) but I think that if they collect this info from web page to these headers so they need to collect it through functions located on page and interesting think that two functions init.js and secssdk.js or something like this are cached after you get it from page and they call it unvisiable to every like or sub.If someone can see wtf they doing with them will be very appreciated because I know how generate all params bogus,mstoken,signature except these headers,and main thing that we cannot generate them because you can’t reverse shape security algorithm main think is to understand the cascade of functions from which tiktok send them info and get these params and after resend them again when you trying to sub or like, and repeat them carefully.

**Comment by frogc0de** [comment]
There is something strange happening, I want someone to check this. When I follow a random user, I am able to see the post request in mitm proxy, after this I unfollow the user and replay the request in mitm proxy and it follows the user again. Now here is the strange thing, when I copy all the parameters from the post request into a python file and make the same exact request with cookies, headers and etc. it gives a success message, but for an odd reason does not actually cause the user to get followed.

**Comment by frogc0de** [comment]
> > I think the best way to get this to work is not by using the device api but the web api because it is easier to inspect it.
> 
> Web api have security headers for like and sub from shape security and it is hard to understand how they get it,because they use other service to analyse many data of web fingerprint with neural network(f5 shape security) but I think that if they collect this info from web page to these headers so they need to collect it through functions located on page and interesting think that two functions init.js and secssdk.js or something like this are cached after you get it from page and they call it unvisiable to every like or sub.If someone can see wtf they doing with them will be very appreciated because I know how generate all params bogus,mstoken,signature except these headers,and main thing that we cannot generate them because you can’t reverse shape security algorithm main think is to understand the cascade of functions from which tiktok send them info and get these params and after resend them again when you trying to sub or like, and repeat them carefully.

I meant that it could possibly be easier to use an automated webdriver to follow/unfollow the user. Basically, logging in with google, going to the user page, finding the follow button and clicking it.

**Comment by frogc0de** [comment]
I will most likely not be able to solve this since my intention with this api was not really for botting user accounts.

**Comment by freevbuckz** [comment]
> I will most likely not be able to solve this since my intention with this api was not really for botting user accounts.

Okay thanks, no problem. Thanks for the attempt though

**Comment by Petr2282** [comment]
> > > I think the best way to get this to work is not by using the device api but the web api because it is easier to inspect it.
> > 
> > 
> > Web api have security headers for like and sub from shape security and it is hard to understand how they get it,because they use other service to analyse many data of web fingerprint with neural network(f5 shape security) but I think that if they collect this info from web page to these headers so they need to collect it through functions located on page and interesting think that two functions init.js and secssdk.js or something like this are cached after you get it from page and they call it unvisiable to every like or sub.If someone can see wtf they doing with them will be very appreciated because I know how generate all params bogus,mstoken,signature except these headers,and main thing that we cannot generate them because you can’t reverse shape security algorithm main think is to understand the cascade of functions from which tiktok send them info and get these params and after resend them again when you trying to sub or like, and repeat them carefully.
> 
> I meant that it could possibly be easier to use an automated webdriver to follow/unfollow the user. Basically, logging in with google, going to the user page, finding the follow button and clicking it.

You underestimate the power of tiktok).As I said before they collect all fingerprint params in these headers and send it to shape security they have neural network,so if you mainly bypass the first easiest defence (hide webdriver) and start liking post using many accs and proxies in about 50-100 likes it will ban this video from web liking to all.

**Comment by frogc0de** [comment]
If you want to make an api that uses a single account to like videos for any purpose, then it should be possible and simple (by using webdriver). If you are trying to make some spam commenter/liker program than this would be quite challenging and personally I am not willing to make botnets. The main purpose of this api is to be able to collect data for analytical use and not control user accounts.

**Comment by frogc0de** [comment]
Sorry, this API supports scraping only, adding the ability to control a user account is quite complicated.

**Comment by frogc0de** [comment]
Closed this issue because I am unable to solve or implement a script that can control user accounts. If you do find a good and simple solution do let me know.
