### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by shadyplus1** [frogc0de/TikTok-API#5]
Hello, I think the script is no longer working properly

**Comment by frogc0de** [comment]
Possibly the device parameters expired, try setting up new ones https://github.com/frogc0de/TikTok-API#finding-and-setting-device-parameters. If that does not work, then tiktok probably made an update to fix this.

**Comment by frogc0de** [comment]
Seems like this was indeed a problem with titktok because the app was also acting strange. I have checked the code again and everything seems to be working, please let me know if it is not working for you and if it is close this problem.

**Comment by axsddlr** [comment]
> Seems like this was indeed a problem with titktok because the app was also acting strange. I have checked the code again and everything seems to be working, please let me know if it is not working for you and if it is close this problem.

anyway to program a status check so people cant check if their api is down or not

**Comment by frogc0de** [comment]
> > Seems like this was indeed a problem with titktok because the app was also acting strange. I have checked the code again and everything seems to be working, please let me know if it is not working for you and if it is close this problem.
> 
> anyway to program a status check so people cant check if their api is down or not

Yes, I should program a simple status checkup

**Comment by frogc0de** [comment]
I have made a status monitor for the api, it updates every 5 mins and shows the status of each function. I will later provide a more detailed description https://tiktok-api-status.frogcode.repl.co/
